# NumPy Module, week10

1. **Numpy**

  1.1.  **What is NumPy?**

  1.2.  **Creating NumPy Arrays**
      - Creating Arrays from *Python Lists*
      - Creating Arrays using *NumPy Functions*

  1.3.  **Accessing Values**
      - Dimension and Shape
      - Indexing *(Accessing individual elements)*
      - Slicing

  1.4. **Elementwise Operations**

  1.5. **Broadcasting**

  1.6. **Reshaping Arrays**

  1.7. **Matrix Operations**

  1.8  **Reductions (Summarizing Data)**

  1.9  **Loading Data from Files**


<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1. NumPy </h1>

* NumPy is the fundamental package for scientific computing in Python.
* It provides a high-performance multidimensional array object (`ndarray`).
* It offers tools for working with these arrays, including mathematical functions, linear algebra, random number generation, and more.
* NumPy arrays are more efficient (in speed and memory) than standard Python lists for numerical operations.



<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.1 Why Use NumPy? </h1>

* **Speed:** Operations are implemented in C, making them much faster than equivalent Python loops.
* **Memory Efficiency:** NumPy arrays store elements of the same data type contiguously in memory.
* **Convenience:** Provides a vast library of high-level mathematical functions that operate on entire arrays.
* **Foundation:** Many other data science libraries (Pandas, SciPy, Matplotlib, Scikit-learn) are built on top of NumPy.


```python
# Setup: Import the NumPy library
import numpy as np

# Optional: Check the installed version
print(f"NumPy Version: {np.__version__}")
```




## Example#1:

In [2]:
# Setup: Import the NumPy library
import numpy as np

# Optional: Check the installed version
print(f"NumPy Version: {np.__version__}")

NumPy Version: 1.26.1


<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.2 Creating NumPy Arrays? </h1>

NumPy arrays can be created in several ways:

## 1.2.1 Creating Arrays from Python Lists

Use the `np.array()` function.
* A list creates a 1-D array.
* A list of lists creates a 2-D array (matrix).

## Example#2:

In [ ]:
# Create a 1-D array from a list
list_1d = [1, 2, 3, 4]
array_1d = np.array(list_1d)
print("1-D Array from list:\n", array_1d)

# Create a 2-D array (matrix) from a list of lists
list_2d = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
array_2d = np.array(list_2d)
print("\n2-D Array from list of lists:\n", array_2d)

# Another 2D example
list_2d_b = [[2], [3], [5]]
array_2d_b = np.array(list_2d_b)
print("\nAnother 2-D Array (Column Vector):\n", array_2d_b)

## 1.2.2 Creating Arrays using NumPy Functions.

NumPy provides functions to generate arrays:

* **`np.arange(start, stop, step)`**: Creates an array with evenly spaced values. Values start from `start`, increment by `step`, and end *before* `stop`.
* **`np.zeros(shape)`**: Creates an array filled with zeros. `shape` defines the dimensions (can be an integer for 1D or a list/tuple for multi-dimensional).
* **`np.ones(shape)`**: Creates an array filled with ones.
* **`np.identity(n)`**: Creates an $n \times n$ identity matrix (a 2-D array).

## Example#3:

In [ ]:
# Using np.arange
arange_array = np.arange(1, 3, 0.5) # Start=1, Stop=3 (exclusive), Step=0.5
print("np.arange(1, 3, 0.5):\n", arange_array)

# Using np.zeros
zeros_array = np.zeros([3, 3]) # A 3x3 array of zeros
print("\nnp.zeros([3, 3]):\n", zeros_array)

# Using np.ones
ones_array = np.ones(4) # A 1D array of four ones
print("\nnp.ones(4):\n", ones_array)

# Using np.identity
identity_matrix = np.identity(4) # A 4x4 identity matrix
print("\nnp.identity(4):\n", identity_matrix)

<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.3  Accessing Values </h1>

## 1.3.1 Dimension and Shape

* **`np.ndim(array)`**: Returns the number of dimensions (1 for vector, 2 for matrix).
* **`np.shape(array)`**: Returns a tuple representing the size of each dimension (e.g., `(rows, columns)` for a 2D array).



## Example#4:

In [ ]:
# Examples
d = np.arange(1, 3, 0.5)
e = np.zeros([3, 3])
f = np.ones(4)
g = np.identity(4)

print("Array 'd': ndim =", np.ndim(d), " shape =", np.shape(d))
print("Array 'e': ndim =", np.ndim(e), " shape =", np.shape(e))
print("Array 'f': ndim =", np.ndim(f), " shape =", np.shape(f))
print("Array 'g': ndim =", np.ndim(g), " shape =", np.shape(g))

## 1.3.2 Indexing

Accessing individual elements.

* **1-D Arrays**: Use a single index (like Python lists), starting from 0.
* **2-D Arrays**: Use `[row, column]` indexing. Negative indices count from the end.



## Example#5:

In [3]:
# 1-D Array Indexing
a = np.arange(1, 3, 0.5) # a is [1.0, 1.5, 2.0, 2.5]
print("a[1]:", a[1])

b_1d = np.array([2, 3, 5, 7, 11, 13, 17])
print("b_1d[0]:", b_1d[0])
print("b_1d[0] + a[2]:", b_1d[0] + a[2]) # 2 + 2.0

# 2-D Array Indexing
b_2d = np.array([[ 2, 3, 5, 7],
                 [11, 13, 17, 19],
                 [23, 29, 31, 37]])
print("\n2D Array 'b_2d':\n", b_2d)
print("b_2d[0, 0]:", b_2d[0, 0]) # First row, first column
print("b_2d[2, 3]:", b_2d[2, 3]) # Third row, fourth column
print("b_2d[-1, -1]:", b_2d[-1, -1]) # Last row, last column

a[1]: 1.5
b_1d[0]: 2
b_1d[0] + a[2]: 4.0

2D Array 'b_2d':
 [[ 2  3  5  7]
 [11 13 17 19]
 [23 29 31 37]]
b_2d[0, 0]: 2
b_2d[2, 3]: 37
b_2d[-1, -1]: 37


## 1.3.3 Slicing

Accessing individual elements.

Accessing subarrays using `start:stop:step` syntax. Remember `stop` is exclusive.

* **1-D Arrays**: `array[start:stop]`
* **2-D Arrays**: `array[row_start:row_stop, col_start:col_stop]`. Use `:` to select all rows or all columns.

## Example#6:

In [ ]:
# Slicing examples
a = np.array([2, 3, 5, 7, 11, 13, 17])
b = np.array([[ 2, 3, 5, 7], [11, 13, 17, 19],
              [23, 29, 31, 37]])

print("a[1:3]:", a[1:3]) # Elements at index 1 and 2
print("a[3:]:", a[3:])  # Elements from index 3 to the end

print("\nb[0:2, 1:3]:\n", b[0:2, 1:3]) # Rows 0, 1 and Columns 1, 2
print("\nb[:, 1]:", b[:, 1])      # All rows, column 1
print("\nb[-1, :]:", b[-1, :])     # Last row, all columns

<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.4  Elementwise Operations </h1>

Arithmetic operations can be applied directly to NumPy arrays.

## 1.4.1 Operations with Scalars

The operation is applied to every element in the array. NumPy mathematical functions also work elementwise on arrays.



## Example#7:

In [ ]:
# Array-Scalar Operations
a = np.arange(1, 11, 1) # Array [1, 2, ..., 10]
print("Original array 'a':", a)
print("2 * a:", 2 * a)
print("a - 2:", a - 2)
print("a ** 2:", a ** 2)

# Elementwise functions
v = np.arange(0, 1, 0.2) # Array [0.0, 0.2, 0.4, 0.6, 0.8]
print("\nOriginal array 'v':", v)
print("v + 2:", v + 2)
print("np.power(v, 2):", np.power(v, 2)) # Equivalent to v**2
print("np.exp(v):", np.exp(v)) # e^x for each element

## 1.4.2 Operations Between Two Arrays.

If two arrays have the **same shape**, arithmetic operations are performed element by element between corresponding elements.

**Note:** This is *elementwise* multiplication (`*`), not matrix multiplication. For matrix multiplication, use `np.matmul()`.


## Example#8:

In [ ]:
# Array-Array Operations
a = np.identity(4)
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
c = np.diag([1,2,3,4]) # Creates a diagonal matrix

print("Matrix A (identity):\n", a)
print("\nMatrix B:\n", b)
print("\nMatrix C (diagonal):\n", c)

print("\nA + B:\n", a + b) # Elementwise addition
print("\nB * C:\n", b * c) # Elementwise multiplication

<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.5  Broadcasting </h1>

Broadcasting describes how NumPy handles arithmetic operations between arrays of *different* shapes. If the shapes are compatible (following specific rules, often involving dimensions of size 1), NumPy can virtually "stretch" or "duplicate" the smaller array to match the shape of the larger one for the operation.

* Example 1: Array and a 1D array (row) - The row is broadcast across all rows of the 2D array.
* Example 2: Array and a 1D array (column) - The column is broadcast across all columns of the 2D array.
Python





## Example#9:

In [ ]:
# Broadcasting Example 1: 2D + 1D (row)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b_row = np.array([0,1,2,3]) # Shape (4,)
print("Matrix A:\n", a)
print("\nRow Vector b_row:", b_row)
print("\nA + b_row (Broadcasting):\n", a + b_row)

# Broadcasting Example 2: 2D * 1D (column)
c_col = np.array([[0],[1],[2],[3]]) # Shape (4, 1)
print("\nColumn Vector c_col:\n", c_col)
print("\nA * c_col (Broadcasting):\n", a * c_col) # Elementwise multiplication after broadcasting

<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.6  Reshaping Arrays </h1>

The `np.reshape()` function changes the shape of an array without changing its data. The total number of elements must remain the same.




## Example#10:

In [ ]:
# Reshaping Example
a = np.arange(1, 11, 1) # 10 elements
print("Original array 'a' (shape {}):".format(a.shape), a)

# Reshape to 2 rows, 5 columns
b = np.reshape(a, (2, 5))
print("\nReshaped to (2, 5):\n", b)

# Reshape to 5 rows, 2 columns
c = np.reshape(a, (5, 2))
print("\nReshaped to (5, 2):\n", c)

# Reshape to 10 rows, 1 column (column vector)
d = np.reshape(a, (10, 1))
print("\nReshaped to (10, 1):\n", d)

# Attempting an invalid reshape (will cause an error)
# e = np.reshape(a, (5, 1)) # Error: cannot reshape array of size 10 into shape (5,1)
# print(e)

<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.7  Matrix Operations </h1>

## 1.7.1 Operations with Scalars

Use `np.matmul(matrix1, matrix2)` for standard matrix multiplication. The inner dimensions must match.

## Example#11:


In [ ]:
# Matrix Multiplication Example
a = np.array([[1,2,3,4],[5,6,7,8],
              [9,10,11,12],[13,14,15,16]])
b_id = np.identity(4)
c = np.array([[1,2,3], [4,5,6]]) # Shape (2, 3)
d = np.array([[5,-1], [1,0], [-2,3]]) # Shape (3, 2)

print("Matrix A:\n", a)
print("\nMatrix B (Identity):\n", b_id)
print("\nMatrix C:\n", c)
print("\nMatrix D:\n", d)

# A * Identity = A
print("\nnp.matmul(a, b_id):\n", np.matmul(a, b_id))

# (2x3) * (3x2) -> (2x2)
print("\nnp.matmul(c, d):\n", np.matmul(c, d))

## 1.7.2 Inverse and Determinant

The `np.linalg` submodule contains linear algebra functions.
* **`np.linalg.inv(matrix)`**: Computes the inverse of a square matrix.
* **`np.linalg.det(matrix)`**: Computes the determinant of a square matrix.

An inverse exists only if the determinant is non-zero.

## Example#12:


In [ ]:
# Inverse and Determinant Example
a = np.array([[1,1,1,-1], [1,1,-1,1], [1,-1,1,1], [-1,1,1,1]])
b = np.identity(4)

det_a = np.linalg.det(a)
print("Determinant of a:", det_a)

if det_a != 0:
    inv_a = np.linalg.inv(a)
    print("\nInverse of a:\n", inv_a)
    # Verify: a @ inv_a should be close to identity
    print("\nVerification (a @ inv_a):\n", np.matmul(a, inv_a))
else:
    print("\nMatrix 'a' is singular, inverse does not exist.")

det_b = np.linalg.det(b)
print("\nDeterminant of b:", det_b)
if det_b != 0:
     inv_b = np.linalg.inv(b)
     print("\nInverse of b:\n", inv_b)
else:
    print("\nMatrix 'b' is singular, inverse does not exist.")

## 1.7.3 Solving Linear Systems

A system of linear equations like $Ax = b$ can be solved for $x$

if $A$ is invertible: $x = A^{-1}b$.

## Example#13:


In [ ]:
# Solving Ax = b
# System:
# 5x + 15y + 56z = 35
# -4x - 11y - 41z = -26
# -x - 3y - 11z = -7

A = np.array([[5, 15, 56],
              [-4, -11, -41],
              [-1, -3, -11]])

b = np.array([[35], [-26], [-7]])

print("Matrix A:\n", A)
print("\nVector b:\n", b)

# Calculate inverse of A
try:
    A_inv = np.linalg.inv(A)
    print("\nInverse of A:\n", A_inv)

    # Calculate x = A_inv * b
    x = np.matmul(A_inv, b)
    print("\nSolution vector x:\n", x)

    # Verification: A @ x should be close to b
    print("\nVerification A @ x:\n", np.matmul(A, x))

except np.linalg.LinAlgError:
    print("\nMatrix A is singular. Cannot solve the system using inverse.")

<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.8  Reductions </h1>

NumPy provides functions to compute summary statistics over arrays (e.g., sum, max, min, mean, standard deviation).

* **1-D Arrays**: Functions operate on all elements.
* **2-D Arrays**: Functions can operate on all elements, or along a specific axis:
    * `axis=0`: Operates down the columns (reduces rows).
    * `axis=1`: Operates across the rows (reduces columns).
* **`np.sort(array)`**: Returns a sorted copy of the array.
* **`np.argsort(array)`**: Returns the indices that would sort the array.

## Example#14:


In [ ]:
# 1-D Reduction Example
a = np.arange(1, 11, 1) # Array [1, 2, ..., 10]
print("Array 'a':", a)
print("Sum:", np.sum(a))
print("Max:", np.max(a))
print("Min:", np.min(a))

# 2-D Reduction Example
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("\nArray 'b':\n", b)
print("Sum (all elements):", np.sum(b))
print("Sum along rows (axis=1):", np.sum(b, axis=1)) # Sum of each row
print("Sum along columns (axis=0):", np.sum(b, axis=0)) # Sum of each column

# Sorting Example
c = np.array([10, 2, 3, 1, 20, 12, 5])
print("\nArray 'c':", c)
print("Sorted array:", np.sort(c))
print("Indices for sorting:", np.argsort(c)) # Indices of elements in sorted order

<h1 style="font-size:1.5em; font-family: verdana, Geneva, sans-serif; color:#00A0B2">1.9  Loading Data from Files </h1>

The `np.loadtxt()` function can load data from text files (like `.txt` or `.tsv`) into a NumPy array. You often need to specify the delimiter (e.g., `\t` for tab-separated) and the data type.

## Example#15:


In [3]:
# Example: Loading hypothetical 'sales.tsv' data
# First, let's create a dummy file to simulate the example
# In a real scenario, 'sales.tsv' would already exist.
import numpy as np
dummy_file_content = """1001\t234\t51\t726
1002\t98\t453\t132
1101\t156\t12\t87
1102\t92\t154\t424
1201\t89\t78\t456"""

file_name = 'sales.tsv'
with open(file_name, 'w') as f:
    f.write(dummy_file_content)

print(f"Created dummy file: {file_name}")

# Load data using np.loadtxt
try:
    # Assuming columns are: Branch, ProdA, ProdB, ProdC
    data = np.loadtxt(file_name, delimiter='\t', dtype=float)
    print("\nLoaded data:\n", data)

    # Example Calculations based on Example 10.19
    # Calculate sum of sales per branch (sum across columns 1, 2, 3 for each row)
    # Note: data[:, 1:] selects all rows, and columns from index 1 onwards (ProdA, ProdB, ProdC)
    sales_per_branch = np.sum(data[:, 1:], axis=1)
    print("\nTotal Sales per Branch:\n", sales_per_branch)

    # Calculate sum of sales per product (sum down rows for columns 1, 2, 3)
    sales_per_product = np.sum(data[:, 1:], axis=0)
    print("\nTotal Sales per Product (A, B, C):\n", sales_per_product)

except FileNotFoundError:
    print(f"\nError: {file_name} not found. Cannot load data.")
except Exception as e:
    print(f"\nAn error occurred: {e}")

Created dummy file: sales.tsv

Loaded data:
 [[1001.  234.   51.  726.]
 [1002.   98.  453.  132.]
 [1101.  156.   12.   87.]
 [1102.   92.  154.  424.]
 [1201.   89.   78.  456.]]

Total Sales per Branch:
 [1011.  683.  255.  670.  623.]

Total Sales per Product (A, B, C):
 [ 669.  748. 1825.]
